version: '3.1'

services:
  weex-ftp:
    build:
      context: .
      dockerfile: Dockerfile
    image: weex-ftp
    container_name: weex-ftp  
    expose: 
      - "5050:5050"
    env_file: ./.env
    restart: unless-stopped
 